= Cross-Testing Feedback

__Durchführende Gruppe:25__
__Anwendung von Gruppe:26__

== Getestetes System
Welche Aufgabe/Problemstellung löst die Anwendung.

== Fehler-Report
// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Pfad |Parameter |Beschreibung |Rückgabe
| … | … | … | … |
|===

== Sonstiges
* Optik der Anwendung
* Fehlende Features
* Interaktion mit der Anwendung (Usability)

== Buchung
* Die vergangene Daten können trotzdem gebucht werden.Die Buchung kann auch bezahlt werden, aber wird nicht bei der Buchungsübersicht angezeigt.
* Last Minuten Buchungen(von heute) werden nicht angezeigt bei der Büchungsübersicht. Man weiß nicht, ob es schon gebucht ist.
 Trotzdem sind die gebuchte Daten nicht mehr buchbar außer das Anfangsdatums.
* Die Daten von den stornierten Buchungen werden nicht freigegeben sind somit nicht buchbar.
* Es wäre besser, wenn mehr Informationen bei dem  Detail View sichtbar wären als Buchungsübersicht.
* Bei der Bezahlen-Seite kann man mit Kreditkarten mit einem ungültigen Expiry-Date bezahlen.




== Verbesserungsvorschläge
== Buchung
* Es ist schön, dass die Auswahl des Einreisedatums und Abreisedatum überschaubar ist.
* Es wäre schön Hinweise zu geben, dass Nutzer noch nicht eingeloggt ist.
* Für einsprachige Nutzer ist das Deutsch-Englisch schwer zu verstehen.
*
