= Pflichtenheft
:project_name: FeWoDre
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2020          | Jimmy Julian Janujan      | Initiale Version
|===

== Inhaltsverzeichnis
1. Zusammenfassung

== 1. Zusammenfassung
Dieses Dokument repräsentiert das Pflichtenheft des Projekts *FewoDre*. Ziel ist es, eine Übersicht über die zu entwerfende Software zu gewährleisten, welche als Grundlage für die Kommunikation zwischen den Interessenvertretern des Projekts und dem Entwicklerteam dient. Zielstellung ist es, dieses Dokument als Grundlage des Vertrags zwischen dem Auftraggeber und den Entwicklern anzunehmen, weshalb es hinsichtlich seiner Korrektheit und Konsistenz zu überprüfen ist. Folgendes Pflichtenheft beschreit die Anforderungen an das gewünschte System und, in Ansätzen, deren Implementierung durch die Entwickler.

Generell besteht der Anspruch, dass das Pflichtenheft *korrekt*, *komplett* und *konsistent* ist. Da dieses Pflichtenheft bei Abgabe als Maßstab für die Software dient, sollten sämtliche definierten Ziele *erfüllbar* sein. Eine *Rückfervolgung* ist wichtig, da das Pfilchtenheft während des gesamten Entwicklungsprozesses verwendet und als Referenz herangezogen wird. Ferner besteht der Anspruch der einfachen Erweiterbarkait, obgleich Änderungen nach Zustimmung durch die Interessenvertreter auf ein Minumum begrenzt werden sollten.  Da Anforderungen und Umstände konstanten Änderungen unterliegen, sind Anpassungen erwartbar und müssen entsprechend dokumentiert werden.


== 2. Aufgabenstellung & Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen. 


== 3. Produktnutzung
Dieser Abschnitt wird im Folgenden einen Überblick über die geplante Nutzung der Software und dessen Einbettung geben.

Ziel der Software ist es als Web-Shop Kunden der Firma FeWoDre das digitale Buchen von Ferienhäusern in und um Dresden zu ermöglichen. Auf einem Server gehostet soll der Web-Shop rund um die Uhr und unter Nutzung eines Webbrowsers über das Internet erreichbar sein.

Eine Optimierung für folgende Webbrowser steht im Vordergrund:

- Mozilla Firefox, version 55.0.3+
- Google Chrome, version 61.0.3163+

Eine einfache Bedienung des webshops sollte ohne vertieftes technisches Verständnis möglich sein, um eine möglichst breite Zielgruppe anzusprechen. Sämtliche Daten sollen in einer Datenbank persistiert werden und durch den Webshop abfragbar sein.

== 4. Interessenvertreter (Stakeholders)
Nachfolgend sind sämtliche juristische und natürliche Personen aufgelistet, welche mit der Software interagieren oder dessen Anforderungen beeinflussen. Ferner erfolgt eine Priorisierung der Akteure zusammen mit einer Beschreibung ihrer vorrangigen Ziele. Die Priorisierung erfolgt absteigend, wobei 1 als niedrigste und 5 als höchste Priorität zu verstehen ist.

|===
|*Name* |*Priorität* |*Beschreibung* |*Ziele*
|--- |--- |--- |---
|--- |--- |--- |---
|--- |--- |--- |---
|--- |--- |--- |---
|--- |--- |--- |---
|===

== 5. Systemgrenzen und Top-Level-Architektur

=== 5.1 Kontextdiagramm
Das Kontextdiagramm beschreibt die Integration das geplante Systems. Berücksichtigt werden alle Nutzergruppen und deren Zugriff auf das System sowie jegliche Software Dritter, welche auf das System zugreift oder auf die durch unser System zugegriffen wird.

--- PASTE THE DIAGRAM HERE ---

=== 5.2 Top-Level-Architektur


== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|...  |...
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Funktionale Anforderungen

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

== Nicht-Funktionale Anforderungen

=== Qualitätsziele

Dokumentieren Sie in einer Tabelle die Qualitätsziele, welche das System erreichen soll, sowie deren Priorität.

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
