= Test-Plan FeWoDre

== Einführung
Dieser Test-Plan dient der Sicherstellung, dass alle für das Projekt FeWoDre geplanten Komponenten ordnungsgemäß implementiert und den Erwartungen des Kunden entpsrechend funktionieren. Dies wird erreicht durch die Absicherung und Auswertung einer Reihe von unterschiedlichen Tests, wie Integrations- und Unit-Tests. Zur Durchführung der unit und Integrationstests nutzen wir JUnit. Ein Unit-Test beschreiben das Überprüfen der einzelnen Funktionen und Methoden jeder Komponente auf richtige Funktionalität und korrekte Ausführung. Integrationstest beschreiben das korrekte Zusammenspiel der Komponenten untereinander, dazu zählen auch Komponenten wie Salespoint oder Spring.

== Aufbau der Testbezeichner
Die Testbezeichner in diesem Test-Plan sind folgendermaßen zu verstehen:

Der Präfix gibt Auskunft die Art des Tests. Präfix *U* steht für Unit-Tests, Präfix *I* für Integrationstests. Die verschiedenen Testbezeichner sind außerdem einer bestimmten Komponente zugehörig. Die erste Ziffer nach dem Präfix gibt Auskunft darüber. Dabei steht der Präfix *0* für die Komponente *Catalog*, der Präfix *1* für Komponente *Bookings* und der Präfix *2* für Komponente *Accounts*. Die zweite und dritte Ziffer sind die tatsächliche Testnummer und die vierte Ziffer ist für verschiedene Eingaben.
Anschließend inkrementiert sich der Testnummer je nach Anzahl der Tests zur jeweiligen Komponente.

*Bsp.*: *U1001* ist Unit-Test Nr.1 der Komponente Bookings.

== Test Gegenstände
Gegenstand sämtlicher Tests sind sowohl einzelnde Methoden aller Komponenten, als auch das Zusammenspiel jeder Komponente untereinander. Folgende Komponenten sind zu testen:

==== Catalog
Die Catalog-Komponente hält sowohl alle angebotenen Ferienhäuser als auch alle verfügbaren Events. Eine wichtige Rolle spielt hier das korrekte abspeichern alle Informationen der Ferienhäuser und der Events. Dies muss getestet werden.

==== Bookings
Die Booking-Komponente beinhaltet getätigte, stornierte und vergangene Buchungen von Mietern. Auch hier ist die korrekte Persistenz wichtig und muss entsprechend getestet werden.

==== Accounts
Die Account-Komponente trägt alle verschiedenen Nutzergruppen der Plattform. Sowohl Mieter, Vermieter,Eventmitarbeiter als auch Administratoren werden hier verwaltet und gespeichert. Auch diese Funktionalitäten sind zu überprüfen und zu testen.

==== Integrität
Integrität ist keine direkte Komponente der Software. Hierunter ist zu verstehen dass die korrekte Verzahnung der Softwarekomponenten gesichert ist.

== Zu testende Funktionalitäten
|===
| Anwendungsfall | Funktionalität(en)| Beschreibung
| Login & Logout a| 
- Authentifizierung (F0010) | Alle Nutzergruppen sollen die Möglichkeit haben sich anzumelden, um die besonderen Rechte ihrer Accounts wahrzunehmen, und sich abzumelden.
| Registrierung a| 
- Registrieren (F0020)
- Angaben überprüfen (F0021)
| Nutzer der Platform sollen sich als Mieter registrieren können. Administratoren sollen neue Vermieter/Eventmitarbeiter-Accounts erstellen können.
| Ferienhaus ansehen a| 
- Haus Informationen anzeigen (F0120)
- Katalog (F0110)
- Häuser (F0400) | Alle Nutzergruppen sollen die Möglichkeit haben weitere Details über ein Ferienhaus einzusehen.
| Aufenthalt buchen a| 
- Authentifizierung (F0010)
- Bestellungen (F0240)
- Bestellungen erstellen (F0241)
- Buchung (F0200)
- Buchung buchen (F0220) | Mieter sollen die Möglichkeiten haben das gewählte Ferienahus an dem gewählten Zeitraum zu reservieren und durch eine Überweisung zu bestätigen.
| Event dazubuchen a| 
- Authentifizierung (F0010)
- Events (F0500) 
- Events ansehen (F0520) | Mieter sollen die Möglichkeiten haben, Events, die zum Ferienhaus angeboten werden, dazubuchen zu können.
| Buchungen einsehen a| 
- Authentifizierung (F0010) 
- Buchung (F0200)
- Buchung anzeigen (F0210) | Mieter und Vermieter sollen die Möglichkeiten haben, getätigte Buchungen einsehen zu können.
| Buchung bestätigen a| 
- Authentifizierung (F0010)
- Buchung bestätigen (F0243) | Vermieter sollen in der Lage sein getätigte Buchungen von Mietern zu bestätigen.
| Buchung stornieren a| 
- Authentifizierung (F0010)
- Buchung (F0200)
- Buchung stornieren (F0244) | Mieter sollen die Möglichkeit haben, Buchungen zu stornieren. Die erfolgte Anzahlung soll erstattet werden.
| HolidayHome bearbeiten/löschen a| 
- Authentifizierung (F0010)
- Häuser bearbeiten (F0411)
- Häuser löschen (F0412) | Vermieter sollen  die Möglichkeiten haben, die Details der erstellten Ferienhäuser zu bearbeiten und auch löschen zu können.
| Events erstellen/bearbeiten/löschen a| 
- Authentifizierung (F0010)
- Events (F0500)
- Events bearbeiten (F0530)
- Events löschen (F0540) | Eventmitarbeiter sollen  die Möglichkeiten haben, die Events auf der Platform erstellten, bearbeiten und auch löschen zu können.
| Vermieter-/Eventmitarbeiteraccounts verwalten/löschen a| 
- Authentifizierung (F0010)
- Registrieren (F0020)
- Mitglieder erstellen/bestätigen/löschen (F0301) | Administratoren müssen Vermieter- und Eventmitarbeiteraccounts erstellen, bestätigen, verwalten und löschen können.
|===

== Nicht zu testende Funktionalitäten
Dieses Softwareprojekt nutzt die Frameworks Salespoint und Spring. Es wird davon ausgegangen, dass diese Komponenten ausreichend getestet wurden und korrekt funktionieren. Daher werden diese nicht gesondert von uns getestet.

== Herangehensweise

Wir testen zuerst die einzelnen Klassen mit JUnit. Danach testen wir die einzelnen Zusammenhänge der Komponenten an Hand von Integrationstests.
Es wird nach dem Bottom-Up Prinzip vorgegangen, also werden zuerst kleinere grundsätzliche Funktionen getestet, bevor dann immer größere Zusammenhänge getestet werden.

== Umgebungsvoraussetzungen

==== Wird spezielle Hardware benötigt?
Um die Tests durchführen zu können wird ein Endgerät (Computer / Handy / Tablet / etc. ) benötigt, inklusive der zur Operation benötigten Peripheriegeräte (z.B. Maus, Tastatur zur Eingabe, Bildschirm zur Ausgabe, etc.). Außerdem wird idealerweise eine Internetverbindung benötigt um die Tests problemlos vor Ort und lokal ausführen zu können.

==== Welche Daten müssen bereitgestellt werden? Wie werden die Daten bereitgestellt?
Der Kunde muss keine weiteren Daten zur Testausführung bereitstellen.
Zur Testausführung liegen die Integrations- und Unit-Tests im Repository der Anwendung vor. Das Repository kann entweder physikalisch per Datenträger oder übers Internet bereitgestellt werden.

==== Wird zusätzliche Software für das Testen benötigt?
Eine Liste notwendiger Software, um die Anwendung testen zu können.
Die folgende Java-Version ist mindestens erforderlich, um die Tests auszuführen:

* Java 11

Zur Ausführung müssen die Unit- und Integrationstests kompiliert und ausgeführt werden, oder eine beliebige Entwicklungsumgebung wird herangezogen:

* IDE Software (z.B. IntelliJ IDEA, Eclipse, VS Code, etc.)

Die folgenden Versionen der Browser sind jeweils mindestens erforderlich, um Integrationstests bei ausgeführter Anwendung durchzuführen:

* Internet Explorer / Edge 10.0
* Firefox 4.0
* Google Chrome 4.0
* Opera 9.6

==== Wie kommuniziert die Software während des Testens?
Die Tests teilen über die Konsole der Entwicklungsumgebung oder des Betriebssystems die Ergebnisse mit.

== Testfälle und Verantwortlichkeit
Jede testbezogene Aufgabe muss einem Ansprechpartner zugeordnet werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|I0010 |Event absagen a| - Als EventEmployee eingeloggt 
- Es ist ein Event, der EventCompany, vorhanden | button auf Eventseite betätigen       |  Event ist nicht mehr buchbar, eventkosten von Buchungen zurückerstatten
|I0020 |Event erstellen |Als EventEmployee eingeloggt | korrekte ausgefülltes Erstell-Form | es existiert ein neues Event
|I0021 |Event erstellen |Als EventEmployee eingeloggt | inkorrekt ausgefülltes Erstell-Form (leerer String, negative Zahl) | es wird kein Event erstellt, Fehlermeldung
|I0030 |Ferienhaus erstellen |Als Host eingeloggt  | korrekte ausgefülltes Erstell-Form | es existiert ein neues HolidayHome
|I0031 |Ferienhaus erstellen |Als Host eingeloggt  | inkorrekt ausgefülltes Erstell-Form (leerer String, negative Zahl) | es wird kein HolidayHome erstellt, Fehlermeldung
|I0040 |Events für Häuser bestätigen a| - Als Host eingeloggt  
- Es muss ein Ferienhaus existieren  
- Es muss ein noch nich bestätigtes Event in der Nähe des Ferienhauses existieren  | button auf Hausseite betätigen | Event ist nun für Buchungen des Hauses dazubuchbar
|I1000 |Ferienhaus buchen a| - Als Tenant eingeloggt  
- Es existieren buchbare Ferienhäuser |korrekt abgeschlossene Buchung | Es existiert eine neue Buchung
|I1001 |Ferienhaus buchen a| - Als Tenant eingeloggt  
- Es existieren buchbare Ferienhäuser |inkorrekte Buchungsparameter (Haus zu dieser Zeit schon gebucht) | es wird keine Buchung erstellt, Fehlermeldung
|I1002 |Ferienhaus buchen a| - Als Tenant eingeloggt  
- Es existieren buchbare Ferienhäuser |inkorrekte Buchungsparameter (Start- und Enddatum in falscher Reihenfolge) | es wird keine Buchung erstellt, Fehlermeldung
|I1010 |Tenant storniert Buchung a| - Als Tenant eingeloggt  
- Es existiert eine Buchung für eine Ferienwohnung  |button auf Buchungsseite betätigen  | Die Buchung wird als storniert gesetzt, je nach Zeitpunkt wird Geld zurück gezahlt
|I2000 |Registrieren |System wird von unregisteredUser benutzt | korrekte Registierungsdaten eingegeben | es wird eine Registrierungsanfrage erstellt
|I2001 |Registrieren |System wird von unregisteredUser benutzt | inkorrekte Registierungsdaten eingegeben (Account bereits vorhanden) | es wird keine Registrierungsanfrage erstellt, Fehlermeldung
|I2010 |Registrierung bestätigen a| - Admin ist eingeloggt  
- es liegt eine Registrieungsanfrage vor  | Button auf der Tenant-Bestätigungsseite betätigen | Die Registrieungsanfrage existiert nicht mehr
|I2020 |Anmeldung |System wird von unregisteredUser benutzt | korrekte Logindaten eingegeben  | Der Bunutzer ist jetzt mit der ihm zugewiesenen Rolle(ROLE) eingeloggt
|I2021 |Anmeldung |System wird von unregisteredUser benutzt | inkorrekte Logindaten eingegeben (email und password passen nicht zusammen)|…
|I2030 |Ausloggen |System wird von einem angemeldeten User benutzt | in der Navbar auf loggout drücken | Benutzer kann nicht mehr auf erweiterte Rechte drauf zugreifen
|I2040 |Vermieter erstellen |Admin ist eingeloggt | korrekte Daten eingegeben | Es wird ein neuer Host erstellt
|I2041 |Vermieter erstellen |Admin ist eingeloggt | inkorrekte Daten eingegeben(Benutzer existiert schon) | Es wird kein Host erstellt, Fehlermeldung
|I2050 |Eventfirma hinzufügen |Admin ist eingeloggt | korrekte Daten eingegeben | Es wird eine neue Eventfirma erstellt
|I2051 |Eventfirma hinzufügen |Admin ist eingeloggt | inkorrekte Daten eingegeben(Eventfirma existiert schon) | Es wird keine EventCompany erstellt, Fehlermeldung
|I2060 |Eventmitarbeiter erstellen |Admin ist eingeloggt | korrekte Daten eingegeben | Es wird ein neuer Eventmitarbeiter erstellt
|I2061 |Eventmitarbeiter erstellen |Admin ist eingeloggt | inkorrekte Daten eingegeben(Benutzer existiert schon) | Es wird kein EventEmployee erstellt, Fehlermeldung
|…  |…              |…              |…       |…
|===
