= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2020/21
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Tzu-Yu Ku

**Gruppe: 25**

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden

Ich habe mich zum ersten Mal intensiv mit einer objektorientierten Sprache auseinandergesetzt, das
hat mir sehr geholfen die recht abstrakten Prinzipien aus der Softwaretechnologie-Vorlesung besser zu
verstehen, das heißt sowohl die erläuterten Design Pattern und Konzepte zur objektorientierten Programmierung
allgemein als auch die vorgeführten Methoden zur Projektplanung wie CRC-Karten, Objekt-Diagramme, und so vieles
mehr.


== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?

Wir haben uns in zwei Ebenen organisiert. Die Oberste Ebene umfasste alle Teammitglieder mit Janu als unseren Scrum-Master
In dieser Konstellation haben wir uns ein bis zweimal in der Woche getroffen um unsere Pläne zu besprechen
und etwas größeren Proleme zu fixen.
In der zweiten Ebene haben wir uns in zweier Gruppen zusammmengefunden um einzelne Komponenten zu erstellen.
In der zweier Gruppe konnten wir viele kleinere und sogar größere Probleme schnell bewältigen da der jeweils andere schnell
mit Rat und Tat zur Stelle war, da wir beide mit den Komponente und den dahinterstehenden Konzepten vertraut waren.
Kurzgesagt diese Aufteilung finde ich sehr gut weil sie die Vorteile von großen und kleinen Gruppen mit einander verbindet.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?

Die Salespoint-Reference war schön kurz formuliert und hat mir sehr geholfen einen schnellen Einstieg in Salespoint zu
finden aber gleichzeitig fehlte leider etwas detailiertere informatonen die zwar im Javadoc standen, aber dort nur schwer zu
finden waren

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.

Der Projektmanagementteil war zwar sehr hilf- und lehrreich aber sehr aufwändig und damit etwas überverhältnissmäßig zum
gesamten Projekt. Zudem hätte ich noch eine kurze erklärungen zu kleineren schon angefertigten Dateien wie der pom.xml
oder Maven tollgefunden um das Projekt tiefgründiger zu verstehen zu können und auch selbst ein neues starten zu können.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?

Er war sehr hilfsbereit und hat uns gut durch den Ablauf des Projektes geführt.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
