= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2020/21
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Jimmy

**Gruppe: 25**

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden

Ich habe mich zum erstenmal intensiv mit Java und Designpatterns auseinander gesetzt, das
hat mir sehr geholfen mein Wissen in diesen Bereichen zu festigen welches ich durch die Vorlesungen "SoftwareTechnologie" und
"Design-Patterns und Frameworks" erlangte, das das hat mir Freude bereitet und ich möchte mich nun noch etwas intensiver damit
auseinandersetzten. Aber auch die Projektmanagement-Aspekte die in diesen Projekt verfolgt wurden haben meinen sonst recht
chaotischen Gedankengängen geholfen etwas Klarheit zu finden.


== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?

Wir haben uns in zwei Ebenen organisiert. Die oberste Ebene umfasste alle Teammitglieder mit Janu als unseren Scrum-Master
In dieser Konstellation haben wir uns ein bis zweimal in der Woche getroffen um unsere Pläne zu besprechen
und etwas grundlegende Prolemstellungen zu bearbeiten.
In der zweiten Ebene haben wir uns in zweier Gruppen zusammmengefunden um einzelne Komponenten zu erstellen.
Ich fande diese Aufteilung sehr gut weil in den kleinen Gruppen konnte man sich schnell auf Lösungen einigen und die
Gruppen dynamic war etwas unbeschwerter wohingegen es in großen Gruppen einfacher
war Lösungen für grundlegendere Probleme, die z.B. durch Beschränkungen in Html oder Spring auftraten, zu finden und
auch die Ideenfindung lief in der größeren Gruppe schneller ab. Das einzige Problem war das gegen Ende hin die Rollen
der beiden Gruppen etwas verschwammen und wir sehr viel als große Gruppe programmierten das gab uns zwar ständigen
Progress was gut ist, hat aber gleichzeitig ein wenig die Gruppendynamic ausgebremst.


== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?

Die Kurzbeschreibung, die IntelliJ aufgrund der JavaDoc von Salespoint ausgab, war wirklich sehr hilfreich um schnell
Lösungen zu einfacheren Problemen zu finden. Allgemein fande ich Salespoint sehr praktischl, weil es an viele Aspekte dachte
welche ich schnell vergessen hätte. Jedoch empfande ich das Arbeiten mit Salespoint auch ein bisschen als Einschränkung
weil es mir sehr viel flexibilität genommmen hatte und ich dadurch oft die ein oder andere Idee die ich hatte umändern
musste, für einen mehr an Salespoint orientierten Ansatz.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.

Ein bisschen weniger Dokumentationen drum herum wie zum Beispiel die Top-Level-Architektur Diagramme oder Anwendungsfall
Diagramme würde mehr Zeit lassen um mehr Features in das Projekt einarbeiten, was ich persönich als besser genutzte Zeit
ansehen würde. Da viele Diagramme auch den Nutzen von anderen erfüllen.
Zudem wäre eine Einführungsveranstaltung in Spring sehr nützlich gewesen besonders da Spring, meiner Meinung nach,
eine recht von klassischen Java unterschiedliche Syntax verfolgt, was besonders am Anfang schwer nachzufolziehen war.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?

Unser Tutor war sehr nett und hat sich gut um uns gekümmert. Auch hat er immer über uns gewacht damit wir uns nicht in
eine falsche Richtung bewegen. Jedoch kam die Info das er uns recht viele Freiheiten lässt, bei der ausgestaltung des
Projektes, ein klein wenig spät, vielleicht war es aber auch unsere Schuld die Aufgabenstellung bis ins kleinste Detail
genau zu bearbeiten.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?

Es war toll und das Team war echt Klasse, danke.