= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2020/21
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von: Marten Freese**

**Gruppe: 25**

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
//
Während des Praktikums habe ich so einige Dinge gelernt, die sich in verschiedene Bereiche aufteilen lassen.
Zum einen wäre da der Bereich des Projekts an sich. Damit meine ich, dass man nun abseits von der Theorie einmal erleben konnte, wie ein Projekt von Idee des Kunden bis zum fertigen Programm seinen lauf nimmt. Mann konnte nun in der Praxis besser erkennen wozu die einzelnen Phasen der Softwareentwicklung genau gedacht sind und wie diese zusammenarbeiten und ineinander übergehen.

Der zweite Teil zu dem ich viel gelernt habe ist das Programmieren an sich. Dadurch, dass man sich sehr lange und intensiv mit einem Code und Programmiersprache beschäftigt, wird diese immer intuitiver und man eignet sich den einen oder anderen Kniff an. Mit der Zeit fallen einem dann Codestücke auf, die man zu Beginn geschrieben hat, die man mit dem neuen Wissen allerdigs viel effizienter umsetzen kann. 
In diesem Projekt habe ich mich das erste Mal intensive mit html beschäftigt und daher auch in diesem Bereich etwas gelernt. Ähnlich ist es mit den verwendeten Frameworks und anderweitigen Programmen, die wir in diesem Projekt verwendet haben, wie etwa Salespoint oder Spring Boot.
 
Was ich mir sonst noch gewünscht hätte ist, dass ich mich noch ein bisschen mehr mit dem Code meiner Teamkollegen auseinander setzen hätte müssen. Es gibt natürlich Bereiche in denen man zusammen programmiert und sich da absprechen muss. Außerhalb dieser Verknüpfungen unseres Codes gab es da für mich aber wenig Anlässe oder Anreize mich genauer mit dem Code meiner Teamkollegen zu beschäftigen.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
