= Protokoll Gruppe 25

Treffen am 09.11.2020

Ort:      Online via BigBlueButton +
Beginn:   17:00 Uhr +
Ende:     19:30 Uhr

__Schriftführer: Janujan Thanabalasingham__

*Nächstes Treffen:* +
(intern) 11.11.2020, 19:30 Uhr, Online via BigBlueButton +
(offiziell) 16.11.2010, 17:00 Uhr, Online via BigBlueButton

__Teilnehmer:__

- Tzu-Yu Ku
- Jesko Kloß
- Marten Freese
- Julian Böhm
- Jimmy Pöhlmann
- Janujan Thanabalasingham (vorl. Scum Master)
- Fabian Wolf (Tutor und Rolle des Kunden)

== Aktueller Stand
Das zweite Team-Meeting wurde genutzt, um alle bisherigen Ergebnisse der Teilaufgaben jedes Teammitglieds sowohl zur objektorientierten Analyse, als auch zu der Erweiterung des Video-Shops, zusammen zu besprechen und zusammenzutragen. Julian, Jimmy und ich haben bereits erfolgreich ihre jeweilige Aufgabe zur Erweiterung des Video-Shops erledigt, die restlichen Gruppenmitglieder haben ihre Fragen zur Bearbeitung der Aufgaben im Meeting mit unserem Tutor klären können.  (Siehe https://github.com/st-tu-dresden-praktikum/swt20w25/issues/2[#2]). +

Zum Thema OOA hat jedes Teammitglied bereits einen großen Beitrag geleistet. Marten kümmerte sich um erste Akzeptanztestfälle und hat gemeinsam mit Tzu-Yu und Jesko, unter Verwendung der Anwendungsfälle, die Tzu-Yu und Jesko ausgearbeitet haben, den gesamten "Use-Case"-Teil und die Akzeptanztestfälle, sowie alle involvierte Akteure ausgearbeitet. Julian hat sich Gedanken zu den beteiligten Stakeholdern gemacht und einen Entwurf für unser Kontextdiagram angefertigt. Jimmy hat einen ersten Entwurf des Top-Level-Architektur-Diagramms angefertigt. Ich habe einen ersten groben Entwurf der Benutzeroberfläche der Platform unter Verwendung von Bootstrap erstellt. +

Während des Meetings haben wir uns in zwei Gruppen aufgeteilt. Tzu-Yu, Julian und Marten haben gemeinsam nahezu alle Anwendungsfälle zusammengetragen in einem Dokument, um diese im Verlauf der Woche in das Pflichtenheft zu übertragen. Daraus resultieren ebenfalls die Akzeptanztestfälle, die wir unserem Kunden präsentieren werden. Jimmy, Julian und ich haben gemeinsam angefangen die ersten Grundbestandteile unseres Pflichtenhefts auszuformulieren und allen Gruppenteilnehmern ein Gerüst zu erstellen, in das sie ihre Anteile der OOA einbetten können. +



== Retrospektive des letzten Sprints
[option="headers"]
|===
|Issue |Aufgabe |Status |Bemerkung
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/1[#1]     |OOA anfertigen      |Alle Teammitglieder müssen Ihren Teil der OOA gemeinsam im Pflichtenheft zusammentragen.      | 
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/2[#2] |Videoshop erweitern |Es verbleiben noch Teammitglieder, die den Videoshop um die Funktionen einer Aufgabenstellung erweitern müssen. | 
|===


== Planung des nächsten Sprints
Das Pflichtenheft gemeinsam ausformulieren, Klassendiagramm gemeinsam erstellen.
[option="headers"]
|===
|Issue |Titel |Beschreibung |Verantwortlicher |Status
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/1[#1]     |OOA/Pflichtenheft fertigstellen     |siehe https://github.com/st-tu-dresden-praktikum/swt20w25/issues/1[#1]  |alle Gruppenmitglieder                | work in progress
|===
