= Protokoll Gruppe 25

Treffen am 14.12.2020

Ort:      Online via BigBlueButton +
Beginn:   17:00 Uhr +
Ende:     19:30 Uhr

__Schriftführer: Janujan Thanabalasingham__

*Nächstes Treffen:* +
(offiziell) 21.12.2010, 17:00 Uhr, Online via BigBlueButton

__Teilnehmer:__

- Tzu-Yu Ku
- Jesko Kloß
- Marten Freese
- Julian Böhm
- Jimmy Pöhlmann
- Janujan Thanabalasingham (vorl. Scum Master)
- Fabian Wolf (Tutor und Rolle des Kunden)

== Aktueller Stand

Work in Progress

Notizen:
Julian hat an der Karte gebastelt. Zoom function. Stadtteil-Unterscheidung bei Auswahl von Koordinaten auf der Karte. Karte zur Bestimmung des Ortes der Ferienwohnung/des Events.
Janu hat Accountverwaltung für Admins erstellt (work in Progress). Man kann jedem Nutzer per E-Mail kontaktieren, unbestätigte Mieteraccounts bestätigen, und jeden Account-Typen löschen.
Jimmy hat die Verwaltung einer zu tätigenden Buchung erweitert. Buchungen können abgebrochen werden. Wenn vorgeschlagene zubuchbare Events dazugebucht werden, verschwinden nach dem Hinzufügen. Vermieter haben Buchungsübersicht mit verschiedenen Buchungsstati. Buchungsverlauf ist ebenfalls vorhanden. Buchungen können storniert werden. 
Jesko hat jeweils Issues erstellt im Bezug auf seinen Aufgabenbereich der Events und deren Verwaltung. Marten hat zu seinem Aufgabenbereich ebenfalls Issues erstellt und hat damit begonnen einige von diesen zu bearbeiten.

== Retrospektive des letzten Sprints
[option="headers"]
|===
|Issue |Titel |Beschreibung |Verantwortlicher |Status
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/3[#3]     |Prototyp-Teile/OOD anfertigen OOD |siehe https://github.com/st-tu-dresden-praktikum/swt20w25/issues/3[#3]  |alle Gruppenmitglieder                | work in progress
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/4[#4]     |Developer-Dokumentation verfassen |siehe https://github.com/st-tu-dresden-praktikum/swt20w25/issues/4[#4]  |alle Gruppenmitglieder                | work in progress
|===


== Planung des nächsten Sprints

Prototypen so weit wie möglich ausimplementieren und zur Vorstellung vorbereiten. Entwickler-Dokumentation vervollständigen, vor allem die notwendingen Diagramme jeder Komponente entwerfen. Außerdem muss ein solider Test-Plan ausgearbeitet werden.

[option="headers"]
|===
|Issue |Titel |Beschreibung |Verantwortlicher |Status
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/3[#3]     |Prototyp-Teile/OOD anfertigen OOD |siehe https://github.com/st-tu-dresden-praktikum/swt20w25/issues/3[#3]  |alle Gruppenmitglieder                | work in progress
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/4[#4]     |Developer-Dokumentation verfassen |siehe https://github.com/st-tu-dresden-praktikum/swt20w25/issues/4[#4]  |alle Gruppenmitglieder                | work in progress
|https://github.com/st-tu-dresden-praktikum/swt20w25/issues/5[#5]     |Test-Plan ausformulieren |siehe https://github.com/st-tu-dresden-praktikum/swt20w25/issues/5[#5]  |alle Gruppenmitglieder                | work in progress
|===
